### ISSUE TITLE
Change package name

### ISSUE THREAD

**Issue by crandmck** [strongloop/strong-express-metrics#8]
I suggest that this repository be renamed to something like `strong-api-analytics` or `strong-express-api-analytics` because we call the information / feature it provides "API Analytics".  Using "metrics" in the name is confusing, because we use that term to refer to application performance metrics in [Arc](https://docs.strongloop.com/display/SLC/Viewing+metrics+with+Arc) and [slc](https://docs.strongloop.com/display/SLC/Monitoring+with+slc).

Whatever name is chosen, the key thing is at least NOT to use "metrics", but ideally include "API Analytics" in the name.

This is only a factor since the user needs to refer to it manually -- see https://docs.strongloop.com/display/SLC/API+Analytics.

**Comment by OSMeteor** [comment]
like this https://github.com/OSMeteor/expressjs-metrics
